### ISSUE TITLE
Copy code used from Webmozart's path-util into SARB

### ISSUE THREAD

**Issue by DaveLiddament** [DaveLiddament/sarb#108]
webmozart/path-util is deprecated. Copy the code used by SARB into a new file `src/Domain/Utils/Path.php`. Copy test code too and update code to PHP7.3

**Comment by jdreesen** [comment]
See #107

**Comment by DaveLiddament** [comment]
Given SARB's use case it will probably be used in with older code bases. I'm trying to keep SARB's dependencies as wide as possible. It's main dependencies are the Symfony components and my aim is for SARB to work with all supported versions of Symfony components (and PHP versions). The restriction to Symfony filesystem 5.4 is too tight. For adding a new Symfony library it would ideally satisfy the version constraints 4.4 || ^5.0 || ^6.0. Hence this issue to copy code into SARB's codebase.

**Comment by DaveLiddament** [comment]
Fixed by #110
