### ISSUE TITLE
webmozart/path-util usages

### ISSUE THREAD

**Issue by bytestream** [DaveLiddament/sarb#114]
In v1.4.0 webmozart/path-util was removed - https://github.com/DaveLiddament/sarb/pull/110

Usages however still exist: https://github.com/DaveLiddament/sarb/search?q=PathUtil

Resulting in:
```console
$ cat /tmp/phpcpd-sarb.json | php vendor/bin/sarb remove phpcpd.baseline
Unexpected critical error: Class 'Webmozart\PathUtil\Path' not found
```

**Comment by DaveLiddament** [comment]
Thanks for this bug report and for providing details to quickly fix it. 

I think I need to add ComposerRequireChecker to my workflow. Webmozart/path must be a transitive dependency for something pulled in by require-dev.

Really sorry for letting this slip through. Hope it hasn't messed up your day too much.

**Comment by DaveLiddament** [comment]
@bytestream Release https://github.com/DaveLiddament/sarb/releases/tag/1.4.1 has this fixed.

Once again sorry for any troubles this bug caused. Thanks for your help with issue and PR.

**Comment by bytestream** [comment]
> Webmozart/path must be a transitive dependency for something pulled in by require-dev.

Yeah `vimeo/psalm` in `require-dev`

> Hope it hasn't messed up your day too much.

Definitely not :) Have a good Christmas!
