### ISSUE TITLE
Wrong usage of create command validates only after analysis

### ISSUE THREAD

**Issue by domgraziano** [DaveLiddament/sarb#132]
While using a wrong command like so:

```
bin/phpstan analyse -l 9 src/ --error-format=json | bin/sarb create phpstan.baseline

4725/4725 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Failed to parse analysis results. Have you supplied the data for format [sarb-json].
Issue with result [1]. Missing key [file]
```
the error only bubbles up after the analysis is complete.

On large codebases moving the validators before the start of the analysis can make a huge usability improvement.

**Comment by DaveLiddament** [comment]
I'm not sure this is possible... 

When running SARB we first run PHPStan and then pipe the output from PHPStan into SARB. 
Even if SARB fails immediately, it still needs to wait until PHPStan has finished running. 

My understanding of unix pipes might well be wrong though. If you think this should be possible, then please let me know how. 

Thanks
