### ISSUE TITLE
Add Code_Sniffer

### ISSUE THREAD

**Issue by vladyslavstartsev** [DaveLiddament/sarb#26]
It will be nice to add Code_Sniffer here. Why? The same thing as phpstan. If applying for old project, it can show you tons of issues that you have in your code.

**Comment by DaveLiddament** [comment]
Thanks for the suggestion. Is it this tool https://github.com/squizlabs/PHP_CodeSniffer ?

**Comment by DaveLiddament** [comment]
Text output version added in PR #41

**Comment by DaveLiddament** [comment]
Implemented in PR #41
