### ISSUE TITLE
False positive: error introduced since baseline

### ISSUE THREAD

**Issue by JanMikes** [DaveLiddament/sarb#28]
Hi, i am using PHPStan (tried either with text and json format) on file with error, and just copied it as latest errors, created sarb baseline and got false positive.

### Steps to reproduce:
Output of `vendor/bin/phpstan analyse --error-format=raw > reports/phpstan_errors_baseline.txt` (phpstan_errors_baseline.txt):
```
/app/presenters/ExitPresenter.php:165:Cannot access property $brand on bool|Klarka\Item\Item.
```
`cp reports/phpstan_errors_baseline.txt reports/phpstan_errors_latest.txt` to simulate error was not fixed.

Create baseline: `vendor/bin/sarb create-baseline reports/phpstan_errors_baseline.txt reports/sarb_baseline.json phpstan-text-tmp`

And then compare: `vendor/bin/sarb remove-baseline-results reports/phpstan_errors_latest.txt reports/sarb_baseline.json reports/errors_since_baseline.txt -f`

### (false positive) Output is:
```
Baseline uses ResultsParser [phpstan-text-tmp] and HistoryAnalyser [git]
Errors before baseline 1
Errors in baseline 1
Errors introduced since baseline 1

FILE: app/presenters/ExitPresenter.php
+------+---------------------------------------------------------+
| Line | Description                                             |
+------+---------------------------------------------------------+
| 165  | Cannot access property $brand on bool|Klarka\Item\Item. |
+------+---------------------------------------------------------+
```

Here is content of `sarb_baseline.json` if that helps:
```json
{"historyAnalyser":"git","historyMarker":"8f7184af1d682f5ba2acff3e06c2b2196d6f5afc","resultsParser":"phpstan-text-tmp","analysisResults":[{"lineNumber":165,"fileName":"app\/presenters\/ExitPresenter.php","type":"Cannot access property $brand on","message":"Cannot access property $brand on bool|Klarka\\Item\\Item.","fullDetails":"\/app\/presenters\/ExitPresenter.php:165:Cannot access property $brand on bool|Klarka\\Item\\Item."}]}
```

Do you have any idea what am i doing wrong?

**Comment by DaveLiddament** [comment]
Thanks for a detailed bug report. I'm currently in transit, so will have more time to look when I'm back.

However one quick question. Does the code at git hash `8f7184af1d682f5ba2acff3e06c2b2196d6f5afc` have the PHPStan error at line `165` in   `/app/presenters/ExitPresenter.php` 

Probably easiest way to check is checkout a branch at that commit and rerun PHPStan to double check. 

```
git checkout -b tmp-branch 8f7184af1d682f5ba2acff3e06c2b2196d6f5afc
vendor/bin/phpstan analyse --error-format=raw 
```

**Comment by JanMikes** [comment]
Hi @DaveLiddament thank you for your reply!

I have spent some time debugging step by step with xdebug and found out that you were right 👍 

My problem was i had created baseline from previous commit and some of the commits changed the file, so history analyzer moved the error to line 160 and since that even if report files were exactly the same, after running through SARB history analyzer 165 != 160.

This debugging allowed me to understand SARB internals and how it works, so it was useful for me 😄 

Thank you once again and sorry for my dumb mistake 😄

**Comment by DaveLiddament** [comment]
Hi @JanMikes 

No problem at all. I think the failing here is my documentation or limited warnings about taking a baseline whilst code is not fully committed. I too have made this mistake! 

I am wondering if the following would help?

- Better documentation
- At the time of taking a baseline if `git status` lists any files in then the user is alerted?
 
Any thoughts from someone who is trying to use the tool would be greatly appreciated. 

Thanks once again for your input.

**Comment by TomasVotruba** [comment]
Hi, 

I wonder if the line number should be exact number 160 or a bit dynamic, e.g.:

- `%d`
- 160 -/+ 10 %
- order of the number from the top

etc.

**Comment by JanMikes** [comment]
@DaveLiddament very helpful would be if i did not have to commit every change before running against baseline - what i mean is making SARB understand uncommitted changes would be awesome.

Current workflow:
1) Make changes
2) Commit
3) Run PHPStan to create report
4) Run Sarb to compare latest errors against baseline
5) Fix errors i have made against baseline and commit

This workflow results into 2 commits, if i wanted them in single one, i have to rebase and squash.

Better workflow would be:
1) Make changes
2) Run PHPStan to create report
3) Run Sarb to compare latest errors against baseline
4) Fix errors i have made against baseline and commit everything together
(notice that point 2 for extra commit is not necessary anymore).


> At the time of taking a baseline if git status lists any files in then the user is alerted?
I don't think this would help me in this situation, for me this is nice to have

> Better documentation
Well, better documentation is always helpful, i won't lie to you 😄 though despite this small fail with lines (until i get used to it, so maybe this could be described in a better way) it was pretty okay and quick for me to get started

**Comment by DaveLiddament** [comment]
@JanMikes It is only the when you create the baseline that you need all code committed. This is because the baseline needs to know the git commit it was created against. 

The workflow that you have suggested should be how SARB works now, (i.e. you don't have to commit changes since the baseline). I'll double check everything and try and produce a screen cast or similar that might help.

For more info for now check out [this](https://github.com/DaveLiddament/sarb/blob/master/docs/HowSarbWorks.md).
