### ISSUE TITLE
Improve naming of Domain namespace

### ISSUE THREAD

**Issue by DaveLiddament** [DaveLiddament/sarb#4]
See comment left on this PR: https://github.com/DaveLiddament/sarb/pull/2

**Comment by jjok** [comment]
I dunno. I wouldn't worry about it too much. If you can think of a better name to call something now, then change it now. If not, just leave it, and hopefully at some point in the future you'll think of a better name.
The more you work on the project, the more you'll understand the domain, so it'll be easier to tell which things should be there and which shouldn't.
Even if you suspect something's wrong, if you don't know the solution straight away, I would just leave a `//todo` or something to remind yourself.
