### ISSUE TITLE
PHAR distribution by PHIVE

### ISSUE THREAD

**Issue by szepeviktor** [DaveLiddament/sarb#44]
Please consider phar file distribution https://phar.io/

1. create a phar file with https://github.com/humbug/box
1. add GPG signature
1. upload them as release attachments
1. upload your public key to keyservers
1. add a "sarb" alias to https://github.com/phar-io/phar.io/blob/master/data/repositories.xml

**Comment by DaveLiddament** [comment]
For tools like SARB I think [composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin) answers the  dependency conflict problem without the overhead of creating PHAR packages.

I use  composer-bin-plugin extensively on all my client projects for tools like:
- SARB
- PHP CS Fixer
- Lint
- Composer require checker.

NOTE for some tools, e.g. PHPStan, a PHAR ,delivered by a composer package, is the correct way to go.
