### ISSUE TITLE
Add support for deptrac

### ISSUE THREAD

**Issue by smoench** [DaveLiddament/sarb#48]
Hi @DaveLiddament,
you were in contact with some colleagues of mine at the Symfony Live in London.
They told me you are interested in supporting deptrac with SARB.
Deptrac supports the [jUnit format](https://github.com/sensiolabs-de/deptrac#junit-formatter) we might could adapt here. There is still an issue https://github.com/sensiolabs-de/deptrac/issues/205 but should be fixable soon. Otherwise we could introduce another formatter. WDYT?

**Comment by DaveLiddament** [comment]
I think this is a great idea. I've just added deptrac to SARB. The latest release of SARB now supports the `sarb.json` format, see [here](https://github.com/DaveLiddament/sarb/blob/master/docs/SarbFormat.md). Easiest thing would be for deptrac to produce an output in this format. I'll raise an issue on deptrac and push my first attempt as a PR.

**Comment by DaveLiddament** [comment]
@smoench see this PR for a possible solution: https://github.com/sensiolabs-de/deptrac/pull/269

**Comment by smoench** [comment]
Deptrac implemented its own baseline -> https://qossmic.github.io/deptrac/formatters/
