### ISSUE TITLE
Upgrade to be compatible with Symfony 5

### ISSUE THREAD

**Issue by JanMikes** [DaveLiddament/sarb#55]
Hi!

I am working on upgrading composer dependencies and Sarb is limited to Symfony 4.

**Comment by DaveLiddament** [comment]
@JanMikes Try upgrading to version 0.6.0 and you should be able to use with Symfony 5. Let me know if there are any issues.

**Comment by JanMikes** [comment]
<img width="958" alt="Screenshot 2020-01-28 13 18 23" src="https://user-images.githubusercontent.com/3995003/73263377-bc842000-41d0-11ea-9e10-2e2cb2f7798f.png">

Sweet! I was about to send PR today, but u reacted very fast 😄 Thank you! 👍
