### ISSUE TITLE
PHPCS baseline empty

### ISSUE THREAD

**Issue by Ludo444** [DaveLiddament/sarb#62]
Creating baseline for PHPCS results in empty one for me, `vendor/bin/sarb create-baseline /tmp/phpcs.txt phpcs.baseline phpcodesniffer-full`:
```
Baseline created
Errors in baseline 0
```

I was going by https://github.com/DaveLiddament/sarb/blob/master/docs/PhpCodeSniffer.md

Tried also json output for PHPCS but baseline just stays empty. My git repository is clean, everything committed.

```
{"historyAnalyser":"git","historyMarker":"97fe7e1fb7c5be68bccb3f86ff97cfb4fe633f1e","resultsParser":"phpcodesniffer-full","analysisResults":[]}
```

I have suspicion maybe I'm missing something.

**Comment by DaveLiddament** [comment]
Hi @Ludo444 thanks for raising an issue. 

Yes something definitely looks wrong.... 

A couple of questions:

1) When you ran PHP CS to create your baseline, how many errors and how many warnings did PHP CS report? 

2) Is is possible to share the output from PHP-CS (You can DM on me on twitter @daveliddament if you don't want to share it here). 

Hopefully we can get to the bottom of what is wrong with SARB.

Thanks

**Comment by Ludo444** [comment]
sry for no reply, a bit busy, hopefully will get to it this evening

**Comment by Ludo444** [comment]
So it just started to work out of random, not sure if there was something rotten in git repo or something, but I multiple times checked my steps a week ago and was sure I'm doing everything as stated.

Thanks for help.
